sudo: required
dist: trusty
language: node_js
node_js: 7
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run lint
- npm test
- npm run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_6f9e8e37544e_key -iv $encrypted_6f9e8e37544e_iv
  -in key.pem.enc -out key.pem -d
- npm run compress
deploy:
  provider: script
  skip_cleanup: true
  script: npm run webstore-upload
  on:
    repo: heutagogy/heutagogy-chrome-extension
    branch: master
