sudo: required
dist: trusty
language: node_js
node_js: 7
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run lint
- npm test
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run webstore-upload
  on:
    repo: heutagogy/heutagogy-chrome-extension
    branch: master
